<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>My Page</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="{{rootUrl}}global/css/style.css" media="screen" />
<link rel="stylesheet" type="text/css" href="{{rootUrl}}global/css/user.css" media="screen" />

</head>
<body>

<div id="wrap">

<!-- include 'top' -->

<div id="content">
    <div class="left">

        <h1>My profile</h1><br/>
<!-- include 'profile' -->
    </div>

    <div class="right">
        <!-- include 'my_sidebar' -->
    </div>

    <div style="clear: both;"> </div>
</div>

<!-- include 'footer' -->

</body>
</html>
